package com.epam.training.constants;

public enum FacultyName {
	COMPUTER_AIDED_DESIGN,
	INFORMATION_TECHNOLOGIES_AND_CONTROL,
	RADIOENGINEERING_AND_ELECTRONICS,
	COMPUTER_SYSTEMS_AND_NETWORKS,
	INFOCOMMUNICATIONS,
	ENGINEERING_AND_ECONOMICS
}
